### ISSUE TITLE
Create discussion forum / discord / matrix

### ISSUE THREAD

**Issue by znx3p0** [c0dearm/mushin#14]
Hi! Would it be possible to create a forum to discuss about the API and the philosophy of this project? The idea of this project is really nice, but there may be people who want to contribute with code or with their opinions on the current state of the project and its future.

This way it'll be much easier to discuss about what kind of API works best for the general consumers of the library.

**Comment by c0dearm** [comment]
Hi!

I've just created a [Slack workspace](https://mushin-rs.slack.com) with a `#suggestions` channel.

In theory you should be able to join and we can have a chat there. Let me know if it doesn't work and I will send you an invite link, but in theory it should be open for anyone.

I will also add the link to the `Contributing` topic of the `README` in the next commit.

Thanks for the suggestion! :heart:
