### ISSUE TITLE
Implementing backpropagation

### ISSUE THREAD

**Issue by Kerollmops** [c0dearm/mushin#2]
Hey,

I wanted to implement a simple and [basic word2vec neural network in Rust using a skip-gram model](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/), by hand. I remembered [your library from a Reddit post](https://old.reddit.com/r/rust/comments/mm2mnn/using_const_generics_to_build_neural_networks/) and thought about maybe implementing backpropagation in your library. Can you give me some help on where and how I should implement it? I will probably follow [a basic python tutorial on how it works](https://machinelearningmastery.com/implement-backpropagation-algorithm-scratch-python/).

Have a good day!

**Comment by c0dearm** [comment]
Hi! Backpropagation is now automatically implemented by doing reverse autodifferentiation.

The issue is not relevant anymore.
